DROP VIEW Gydytojai;
DROP VIEW "Medicininio iraso view";
DROP MATERIALIZED VIEW Alga;
DROP trigger MaxPacientuPerDiena ON "Medicininis irasas";
DROP trigger MaxKvalifikaciju ON Gydytojas;
DROP INDEX "Paciento Ligonine Index";
DROP INDEX "Medicininis irasas Index";
DROP TABLE "Gydytojo Ligonine";
DROP TABLE "Paciento Ligonine";
DROP TABLE Gydytojas;
DROP TABLE Ligonine;
DROP TABLE "Medicininis irasas";
DROP TABLE Pacientas;
